import type { Metadata } from "next";
import { Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Schoolbell } from "next/font/google";
import { IBM_Plex_Mono } from "next/font/google";
const schoolbell = Schoolbell({
  subsets: ["latin"],
  weight: "400",
});
const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${ibmPlexMono.className} text-lg tracking-wide min-h-screen flex flex-col items-center`}>
        <header className="flex flex-col items-center py-6 space-y-3">
          <h1 className={`text-9xl text-red-800 ${schoolbell.className}`}>
            Peluchitowos
          </h1>

          <nav className="flex gap-6">
            <Link
              href="/productos"
              className="text-red-800 text-lg hover:text-red-500 transition"
            >
              Productos
            </Link>

            <Link
              href="/creador"
              className="text-red-800 text-lg hover:text-red-500 transition"
            >
              Creador
            </Link>
          </nav>
        </header>

        <main className="w-full max-w-4xl px-4">
          {children}
        </main>
      </body>
    </html>
  );
}